package main

import "testing"

func TestRsaEncrypt(t *testing.T) {
	// Test cases are generated by JavaScript.
	cases := []struct {
		msg, encrypted string
	}{
		{"123456", "192ad42b38fcc7bfda040bd553931154bc35cbfd38b26e7a6a05b3a1fcc17a7b93b68dfaf1ddb547b333c4c8d3f2236040ba49be208a976a9ae2778e43ccee52218c93e33227e879482c72add33604cb47136258c4de08a5752186c82b7987d9000a1f702587c6cb1d4596072041553325a1facf500afdf7e2442f1852a54c64"},
		{"qwerty", "87046cb9b5cf02c2310873d8664beac6b4387ac836d32352723e7577de2c5c599e3fd33b2542028afb35b9b6cf775a5db140dbad62e505c4d854027b14fd6809a50a6a4e5edd4ca1598db74fb55f04f62e8ebc5fd118b81ffb972aaf503e66b018c5a59787725feb1812c5b2d2eb2710a714cc092b5372408a1f3f011611deb4"},
		{"890iop", "3ebb2eea62af82923638453778c565e105545eed46e9a90256eb0ff664ada0d62799403ade8db6f42c0c437ac0acc9226e9b279d0f74956c429a8eb16415e2baa2819004ade253f959a12f4329d24bba7d3bc3cb687ea3d7665cf4d91b435c60d426a9853a48b0fc3f5926ee7be4d4e099a4051df96f3cd800568479170d124a"},
	}
	pub := NewRsaPublicKey(RsaPubKeyExp, RsaPubKeyModHex, 0)
	for i, c := range cases {
		result := RsaEncrypt(pub, c.msg, 16)
		if result != c.encrypted {
			t.Error(i+1, result)
		}
	}
}
